version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    ports:
      # HOST:CONTAINER
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5

  web:
    build: .
    command: python converter_app/manage.py runserver 0.0.0.0:8000
    container_name: web_app
    ports:
      - "8000:8000"
    env_file:
      - ./.local_envs
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: {}
