# Generated by Django 4.1 on 2022-08-27 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prices",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 27, 20, 42, 34, 208459, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="prices",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 27, 20, 42, 34, 208096, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="prices",
            unique_together={("product", "currency_country", "slug_code")},
        ),
    ]
