# Generated by Django 4.1 on 2022-08-27 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0002_prices_create_date_prices_update_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prices",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 27, 20, 43, 18, 839971, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 27, 20, 43, 18, 839620, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
