# Generated by Django 4.1 on 2022-08-28 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0003_alter_prices_create_date_alter_product_create_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prices",
            unique_together={("product", "slug_code")},
        ),
        migrations.AlterField(
            model_name="prices",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
